### ISSUE TITLE
Fix the horrible issue with binary_search_raw

### ISSUE THREAD

**Issue by foxnewsnetwork** [foxnewsnetwork/tsundere#1]
binary search was implemented so we can have proper insert and reads in log time, but it's working. Please pass the tests in array_spec.rb

**Comment by trevor-umeda** [comment]
Changed a test so it accurate reflects what should happen.
Also got the search/insert to work sort of?

7/10 times it passes for me, which means there is some edge case in there where it's not working right. I'll try to fix it later...

**Comment by trevor-umeda** [comment]
Hah fixed it 100%. All tests pass legitly

**Comment by foxnewsnetwork** [comment]
hurray! If it passes then we're good. Added you (using your email trevor.umeda@gmail.com, let me know if this ISN"T your email for rubygems) to the authors list and replaced > operator in array.rb with yield. closing this because it's fixed.
